### ISSUE TITLE
Create bootstrapping ability

### ISSUE THREAD

**Issue by mblayman** [TechFrederick/community#85]
A fresh clone will have a hard time getting local data going. It will be possible to run `uv run manage.py fetch_events`, but since a local db won't have the groups, the `fetch_events` command will have no groups to pull from.

Since the site data is public, we can:

* [ ] Make a groups API endpoint to fetch the groups (i.e., https://community.techfrederick.org/api/v1/groups)
* [ ] Add a Makefile target that will 1) migrate, 2) pull from the endpoint to upsert groups (upsert for idempotency), and 3) trigger `fetch_events` to pull relevant events from the event source.
* [ ] Document how to bootstrap for new people

DRF is cool, but I think it's probably overkill. We can do some hand-rolled serialization to build the groups endpoint and return a `JsonResponse`.

**Comment by greg-meinecke** [comment]
Worked on this a bit last night, will get a pr up tonight or tomorrow.

**Comment by mblayman** [comment]
I've invited you to the TechFrederick organization so that it will be easier for you to contribute to this repo (you could self-assign in the future).

**Comment by greg-meinecke** [comment]
PR up. I haven't used issues a ton so let me know if I need to change anything up.
